### ISSUE TITLE
Access control

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#12]
PDB admin and curators should have access to edit all entries, where as data creators (depositors) should only have access to the entries they created. As per PDB policy, data creators should not have any access to entries that they did not create.

**Comment by carlkesselman** [comment]
I have a standard policy that will do this. I will add.

One clarification.  Do you want only write access restricted, or read access too?

Carl


Sent from my iPad

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA <x-apple-data-detectors://1/0>  90292-6695<x-apple-data-detectors://1/0>
Phone:  +1 (310) 448-9338<tel:+1%20(310)%20448-9338>
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl


On Nov 26, 2019, at 7:20 AM, Brinda Vallat <notifications@github.com> wrote:

﻿

PDB admin and curators should have access to edit all entries, where as data creators (depositors) should only have access to the entries they created. As per PDB policy, data creators should not have any access to entries that they did not create.

**Comment by brindakv** [comment]
Read access should be restricted too.

**Comment by carlkesselman** [comment]
Ok.  This is a bit harder.  In that case we need to define a curation workflow as I assume at some point the data will need to be released.  I would suggest we write this down so we are clear on what is supposed to happen.

Carl


Sent from my iPad

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA <x-apple-data-detectors://1/0>  90292-6695<x-apple-data-detectors://1/0>
Phone:  +1 (310) 448-9338<tel:+1%20(310)%20448-9338>
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl


On Nov 26, 2019, at 7:38 AM, Brinda Vallat <notifications@github.com> wrote:

﻿

Read access should be restricted too.

**Comment by brindakv** [comment]
Sure, we should discuss the curation workflow. But release is not something we need to worry about. That will be handled by the PDB.

**Comment by carlkesselman** [comment]
Well, at this point you have things so that nobody can see anything…. is that really what you want?  I think that would be counter productive……

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Nov 26, 2019, at 7:53 AM, Brinda Vallat <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure, we should discuss the curation workflow. But release is not something we need to worry about. That will be handled by the PDB.

**Comment by brindakv** [comment]
The reason for restricted access is that people submit their data to PDB before publication, get an accession code and use it in their publication. Until the authors approve or until the paper is reviewed and published, the data needs to be private with access to only the depositor and the PDB admins / curators. After publication, it is released. 

Lets create a workflow that includes public release. But how and when release is managed will need to be discussed.

**Comment by hongsudt** [comment]
Duplicate with #21.
