### ISSUE TITLE
ACL for entry.Workflow_Status

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#128]
On both catalogs `99` and `50`, `pd-submitter` is able to choose workflow status that should only be allowed for `pdb-curators`: `Submission_Complete`, `Hold`, `Release_Ready`, `REL`. 

![Image](https://user-images.githubusercontent.com/15000874/214980036-0b46cb13-112f-47d6-9bc3-98b2febd12c6.png)

**Comment by brindakv** [comment]
Same issue on production too.

**Comment by hongsudt** [comment]
This is a frontend issue. Though submitters can see it, the system will throw an error if they choose the wrong ones. 

@svoinea this issue can be addressed through annotation.  There is a $session object that you can use to check for groups, then we can use the domain filter to apply based on the groups. 

First check if a user is in "pdb-admin, pdb-curators, isrd-staff, isrd-system" then don't apply domain filter, else if a user is in "pdb-submitters", apply domain filter pattern to only show "PSB_Submitter_Allow", else don't apply.
 
@RFSH what happens if the domain_filter is empty? Does the annotator need to guard against it?

**Comment by RFSH** [comment]
@hongsudt  If the given pattern produces an empty string, it will be ignored (as if the annotation is not even defined).

**Comment by brindakv** [comment]
Fixed on both dev and production.
