### ISSUE TITLE
Citation year is displayed with a comma

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#13]
In the Citation table, the data in the year column is displayed with a comma. For example, in PDBDEV_00000001, the year 2014 is displayed as 2,014. The format for this column should be YYYY.

**Comment by svoinea** [comment]
This problem is fixed now.

By default, integer values are displayed with commas every 3 digits from the right.

If you want the raw value, you need to define the annotation with the column name having an underscore "_" prefix.

For the mentioned case, in the `column_annotations`, you should defined for the `year` column:
```
    'year': {
        chaise_tags.column_display: {
            '*': {
                'markdown_pattern': '{{_year}}'
            }
        }
    },
```
@brindakv Please dump the "new"  `PDB:citation` table such that the new annotation will not be lost.

**Comment by svoinea** [comment]
The problem was fixed.
