### ISSUE TITLE
Creating new records involving composite foreign keys

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#17]
I was trying to create a new record in the "Ihm Entity Poly Segment" table of PDBDEV_00000001 (see screen shots below). The "molecular entity begin" and "molecular entity end" records are composite foreign keys and offer a pull down list to choose from. However, the options provided are not limited to PDBDEV_00000001, but show all the entries in the database. This is incorrect and we should restrict the pull down list to the current entry (PDBDEV_00000001) alone. 

This is not an access control issue, even PDB admins should not be allowed to pick a wrong record.

**Comment by brindakv** [comment]
![Screen Shot 2019-11-27 at 3 18 41 PM](https://user-images.githubusercontent.com/15000874/69757115-1feac680-112a-11ea-941b-c99a7589576d.png)
![Screen Shot 2019-11-27 at 3 16 55 PM](https://user-images.githubusercontent.com/15000874/69757124-224d2080-112a-11ea-8283-2e13f58ac0f4.png)

**Comment by svoinea** [comment]
This problem is fixed now.

It needed to define the `tag:isrd.isi.edu,2016:foreign-key` annotations with the `domain_filter_pattern` payload for the `ihm_entity_poly_segment_mm_poly_res_label_begin_fkey` and `ihm_entity_poly_segment_mm_poly_res_label_end_fkey` foreign keys of the `ihm_entity_poly_segment` table.

@brindakv Please dump the "new" `PDB:ihm_entity_poly_segment` table such that the new annotations will not be lost.

You will see in the `fkey_defs = ` section the two annotations I defined:
```
    em.ForeignKey.define(
        ['structure_id', 'entity_id', 'comp_id_begin', 'seq_id_begin'],
        'PDB',
        'entity_poly_seq', ['structure_id', 'entity_id', 'mon_id', 'num'],
        constraint_names=[['PDB', 'ihm_entity_poly_segment_mm_poly_res_label_begin_fkey']],
        annotations={
            chaise_tags.foreign_key: {
                'template_engine': 'handlebars',
                'domain_filter_pattern': '{{#if _structure_id}}structure_id={{{_structure_id}}}{{/if}}'
            }
        },
        acls={
            'insert': ['*'],
            'update': ['*']
        },
        on_update='CASCADE',
        on_delete='SET NULL',
    ),
    em.ForeignKey.define(
        ['structure_id', 'seq_id_end', 'entity_id', 'comp_id_end'],
        'PDB',
        'entity_poly_seq', ['structure_id', 'num', 'entity_id', 'mon_id'],
        constraint_names=[['PDB', 'ihm_entity_poly_segment_mm_poly_res_label_end_fkey']],
        annotations={
            chaise_tags.foreign_key: {
                'template_engine': 'handlebars',
                'domain_filter_pattern': '{{#if _structure_id}}structure_id={{{_structure_id}}}{{/if}}'
            }
        },
        acls={
            'insert': ['*'],
            'update': ['*']
        },
        on_update='CASCADE',
        on_delete='SET NULL',
    ),
```

**Comment by brindakv** [comment]
I dumped the new `PDB:ihm_entity_poly_segment` table and groups is empty. Is that intentional?

**Comment by svoinea** [comment]
No. It should have at least the `pdb-curator` which is used by:
```
    em.ForeignKey.define(
        ['Owner'],
        'public',
        'Catalog_Group', ['ID'],
        constraint_names=[('PDB', 'ihm_entity_poly_segment_Owner_fkey')],
        acls={
            'insert': [groups['pdb-curator']],
            'update': [groups['pdb-curator']]
        },
        acl_bindings={
            'set_owner': {
                'types': ['update', 'insert'],
                'scope_acl': ['*'],
                'projection': ['ID'],
                'projection_type': 'acl'
            }
        },
    ),
```
Can you check if your generated `ihm_entity_poly_segment.py` file has the above code?

I was doing the dump of the entire catalog, and the `groups` of the `ihm_entity_poly_segment.py` file is unmodified.

**Comment by hongsudt** [comment]
@brindakv @svoinea is this still an issue?

**Comment by brindakv** [comment]
@svoinea I tried to redo the same process of adding a row to the `Ihm Entity Poly Segment` table. The pull down options are now limited to the current `Entry`, however there is an option on the top of the form to clear the `Structure ID` filter and once the filter is cleared, the pull down list is populated with all options, even those that do not belong to the current `Entry`.

**Comment by brindakv** [comment]
@svoinea the above issue still persists. In addition, if a wrong option from the pull down list is chosen (e.g., something that does not belong to the particular `entry`), the model does not enforce the correction. Also, if the `Structure ID` is cleared once, subsequent tries to fix the data entered does not show the `Structure ID` filter.

**Comment by hongsudt** [comment]
2 issues: 
- model changes e.g. adding fks to ensure column value consistency
- check the UI for domain_filter whether the constraints can be clear.

**Comment by svoinea** [comment]
Issue was fixed by redefining the FK annotations as:
```
        "tag:isrd.isi.edu,2016:foreign-key": {
          "template_engine": "handlebars",
          "domain_filter_pattern": "{{#if _structure_id}}*::facets::{{#encodeFacet}}{\"and\":[{\"source\": \"structure_id\", \"choices\": [\"{{{_structure_id}}}\"], \"hidden\": true} ] }{{/encodeFacet}}{{/if}}"
        }
```

**Comment by hongsudt** [comment]
The above composite fks (i.e. `ihm_entity_poly_segment_mm_poly_res_label_begin_fkey` and `ihm_entity_poly_segment_mm_poly_res_label_end_fkey` will not ensure that the item selected by FKs in Chaise UI are what entered in the DB. 

When a single column (i.e. structure_id) is involved in multiple FKs, chaise can cobble up the fk values. In the above example, the structure_id is set to the parent structure_id (PDBDEV_00000001), the subsequent fk pickers e.g. the `ihm_*_begin_fkey` ignore structure_id column but set the rest of the composite keys columns based on the selected fk value.  For example, if the selected `_ihm_*_begin_fkey` is (PDBDEV_00000002, A, B, C). 

If the assigned columns (associated with composite fkey) e.g. (PDBDEV_00000001, A, B, C) happen to accidentally be in the referenced (i.e. leaf) table , then the row will be successfully  created, but with the unintended FK. If the composite key is not in the referenced table, then Chaise will throw an error. 

One way to solve this problem is to use RID column to refer to a specific row in the leaf table. E.g. instead of  creating this fk `['structure_id', 'entity_id', 'comp_id_begin', 'seq_id_begin']`, use `['structure_id', 'entity_policy_seq_rid']` instead. This FK will detect the inconsistency of structure_id and entity_policy_seq row that corresponds to the wrong structure_id. 

This problem should only exist when inserting a row through Chaise (as the intended FK is inconsistent with what's updated). If the fk picker doesn't allow `domain_filter`  to be unselected, then the Chaise solution should be sufficient. Otherwise, we should also modify the model to prevent this accident from happening.

**Comment by svoinea** [comment]
I have defined in the `ihm_entity_poly_segment` table the `Entity_policy_seq_rid` column and the FK:
```
ihm_entity_poly_segment_RID_Entity_policy_seq_rid_fkey FOREIGN KEY (RID, Entity_policy_seq_rid) REFERENCES entity_poly_seq(RID, structure_id) ON UPDATE CASCADE ON DELETE SET NULL
```
In the `entity_poly_seq` table I have defined the PK:
```
entity_poly_seq_RID_structure_id_key UNIQUE CONSTRAINT, btree (RID, structure_id)
```

**Comment by hongsudt** [comment]
This is old. I assume that it is fixed and I am not closing the issue.
