### ISSUE TITLE
Workflow updates for validation reports

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#171]
- [x] Store validation reports on hatrac: 
 - generated/uid/{entry-RCB}/   (reader)
   - entry/id/{entry-id}/
     - validation_error/{entry-id}_error.cif or {entry-id}.cif-diag.log or {entry-id}.cif-parser.log
     - final_mmCIF/{accession_ID}.cif
     - validation_report/{accession_ID}_full_validation.pdf
     - validation_report/{accession_ID}_summary_validation.pdf
     - validation_report/{accession_ID}_html.tar.gz
 - [x] Create validation reports at specific steps in the workflow
   - during `Submission Complete` → `HOLD` 
   - during `Release Ready` → `REL`
  - [x] Update file metadata / annotations to make them available on ermrest and chaise (see #169)

**Comment by brindakv** [comment]
Updated on catalog 99.

**Comment by brindakv** [comment]
Looks good on `dev`.

**Comment by brindakv** [comment]
When user goes through the deposition workflow, the status is updated to `mmCIF Created` twice. Once after `Submit` and second time incorrectly after `Submission Complete`. Re-triggering `Submission Complete` another time time moves the workflow to `HOLD`.

**Comment by brindakv** [comment]
The workflow is now fixed on `dev`.

**Comment by brindakv** [comment]
@monica81567 Please test the validation report generation workflow on `dev`. Specifically, `HOLD`, `REL`, back and forth.

**Comment by brindakv** [comment]
`Process status` still says `in progress generating accession code` when accession code and mmCIF file are already available and validation reports are still being generated. Validation report generation is the rate limiting step here. Consider updating ermrest (and in turn chaise) after all sub-steps in a workflow step is completed.

**Comment by hongsudt** [comment]
The task has to set Processing Status to in-progress at the beginning of
the processing step to signal that it is being worked on.  The best option
is to delay updating armrest status e.g. accession code at the end of the
step.

However, unless this is an easy change, I would not focus on fixing this
problem as in most cases, nobody is going to tightly monitor the state of
entry.. We can work on this later when we have resources.

@Serban Voinea ***@***.***> can you move the validation report up
before dealing with accession code?  If so, then let's just do that.

**Comment by svoinea** [comment]
The values `In progress ...` of the `Processing Status` are set by the script that triggers the backend execution.
The backend is just updating it to `success` or `error`.

Initially, setting the accession code was a separate workflow step doing just that, ending with the `Workflow Status` set to `HOLD`. Later, we decided to extend the step with the system file generation. 

My suggestion is to replace `In progress: generating accession code` with something like `In progress: generating system files`, as it will be less confusing, because most of the time is being spent in the generating of the system files.

The code was already updated before the release such that the `HOLD` and `REL` values of the `Workflow Status` are set after the system files were generated.
