### ISSUE TITLE
Bulk edit does not work for columns that have foreign keys

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#184]
There seems to be a global bug in the dev and production systems with bulk edit. 

`Set value for all records` doesn't work for an attribute with a foreign key. It brings up the parent table but shows empty values in the parent table and so there is nothing to choose from.

The problem only exists for fkeys to PDB tables. It works for fkeys to vocab tables.

**Comment by hongsudt** [comment]
Can provide detail on how to reproduce this? Which is the main table and
which fkey columns are you try to do set vall?

**Comment by brindakv** [comment]
This happens on several different tables. 

For example, see table `Instances of molecular entities` in entry `D_2-RG82` on production. 

Editing one row in this table allows you to choose a molecular entity for the `Entity Id` column from the `Molecular Entities` table (foreign key). 

But if you choose bulk edit for the same table and try to `Set value for all records`, the `Molecular Entities` table is empty. `Show filter panel` doesn't work either.

**Comment by brindakv** [comment]
Thanks @RFSH. I just want to add that this used work earlier and was a very useful and important feature for us. It is only recently that it stopped working. Additionally, the `Structure Id` column is not empty and has the same value for all records in the bulk edit form. 

There is also another example where this works in a different manner currently. This happens when the attribute is not mandatory unlike the `Entity Id` in the previous example, which is mandatory: 

See this recordedit link: 
https://dev-aws.pdb-dev.org/chaise/recordedit/#99/PDB:software/*::facets::N4IghgdgJiBcDaoDOB7ArgJwMYFM6JHQBcAjdafEABQBEAhEAGhFQDMiB3MDHAfSSIY0WIpj4BLKL1YBrHAE8QAXQC+zAEoBJGsuZYAFinG4klAEwBaAMoAJAGIBNZStVA@sort(RID)?pcid=record&ppid=1rtx28wd1s0f1ffi2iru1f4k

Choose `Set value for all records` for `Citation Id`. This brings up the values in the parent table for all existing records without filtering for `Structure Id`. But `Show filter panel` can be used to narrow it down to the `Structure Id` of interest.

**Comment by brindakv** [comment]
@RFSH If you can send me your globus id, I can give you permission to view/edit these records.

**Comment by hongsudt** [comment]
No no.. let's not do that. There should be a bug in the ACL since the
isrd_staff is supposed to have admin access on dev, and maybe curator
access (?) on production.

**Comment by RFSH** [comment]
@brindakv I don't know much about the PDB model and the decisions made for the models. But the `Citation Id` example you mentioned is different from the case I mentioned. This foreign key only involves `Software` and `Citation` tables, so the `Structure Id` input is not involved.

This bug is only related to cases where we use the `domain_filter` annotation to narrow the offered options for a foreign key input. This annotation is written based on the values in the form. "select all" doesn't belong to any specific forms, so we shouldn't offer it in the general case. For example, on the `PDB:ihm_starting_model_seq_dif` table, assume that in one form, `struct_id=1` and the other, `struct_id=2`. `Asym Id`  for each form will display different options, so we shouldn't offer the "select all" feature in this case.

I understand that in the PDB case where you already have the same `Structure Id` for all the forms, being able to do the "select all" makes sense. So, I will generate an issue in the chaise to discuss this further and see if we can improve this for PDB.

P.S. We were probably naively picking the values from the first form in the previous implementation. That's why it was working correctly for PDB. But that's dangerous, as users can bypass the annotation check and store invalid data (in the example I mentioned above, you would see the same options for both forms, which is wrong).

**Comment by brindakv** [comment]
Thank you for the detailed explanation @RFSH. I understand the problem. 

In our case though, having an option to handle this when the `Structure Id` is the same for all the forms will solve the problem. This is typically our use case and therefore is a very useful feature for us.

**Comment by brindakv** [comment]
Comment out the `domain filter` for a temporary fix.

**Comment by RFSH** [comment]
@brindakv 
The changes that we've described in https://github.com/informatics-isi-edu/chaise/issues/2397 have been merged, and are deployed to the dev server now.

As long as the selected values for all the forms match, you should be able to proceed without any issues. If we detect any inconsistencies, we show an error when you attempt to pick a value in the "set all values" input.

**Comment by brindakv** [comment]
Thank you for quickly addressing this issue @RFSH. 

@svoinea Please let me know when this can be tested on `dev`.

**Comment by hongsudt** [comment]
You should be able to test it on the dev server now.

**Comment by brindakv** [comment]
Thanks @hongsudt. 

@monica81567 Please test bulk editing fkey records on `dev`.

**Comment by brindakv** [comment]
I tested on `dev` and it works well when the bulk edit records have the same `structure_id`, which is our use case. When `structure_id` differs for the bulk edit records, chaise throws an error. @monica81567 please add your comments when you are done testing. 

Nicely done! Thanks @RFSH.

**Comment by brindakv** [comment]
@monica81567 Please test this on `dev`.

**Comment by monica81567** [comment]
Tested fine on dev.  I like the workaround with the select all box.  Thank you.

**Comment by brindakv** [comment]
@svoinea Has this been deployed on production?

**Comment by brindakv** [comment]
@monica81567 Please test on production.

**Comment by brindakv** [comment]
@svoinea This has not been implemented on production.

**Comment by brindakv** [comment]
@monica81567 Please test this on production.

**Comment by brindakv** [comment]
@monica81567 Please test this on production.

**Comment by brindakv** [comment]
Thanks @monica81567.
