### ISSUE TITLE
Namespace for system generated files on HATRAC is incorrect

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#196]
System generated files are now under `pdb-ihm` user namespace and not the `entry-RCB` user namespace on production. 

But the user is able to access and download the system generated files on production. User is able to access other user files as well (both submitted and generated). 

See https://data.pdb-dev.org/chaise/record/#1/PDB:entry/RID=2-XFN2 for an example. 

@brindakv to test more on dev and update this issue.  

@svoinea to make a new code release to be applied on production without validation report generation to address the ACL issue.

**Comment by svoinea** [comment]
The problem was identified in the `chaise` annotation and was fixed on catalog `99` by:
 - on the `entry` table create a composite key `Entry_id_RCB_key [id, RCB]`
 - on the `Entry_Generated_File` table create a new column called `Entry_RCB`
 - on the `Entry_Generated_File` table create a new ForeignKey `Entry_Generated_File_Structure_Id_Entry_RCB_fkey`  `(Structure_Id, Entry_RCB)` references `entry:(id, RCB)`
 - updated the annotations

**Comment by hongsudt** [comment]
@svoinea please close if this problem has been fixed on production.

**Comment by svoinea** [comment]
I have checked and the problem was fixed also on production.
