### ISSUE TITLE
strip pdbx_database_status category upon file upload

### ISSUE THREAD

**Issue by monica81567** [informatics-isi-edu/protein-database#225]
Depositors for 3-9ZDR and 3-9WK4 uploaded files with pdbx_database_status category (see below).  This causes error:
"Table “pdbx_database_status” from mmCIF is not present in the DERIVA database. Possible mismatch versions."
Please strip pdbx_database_status category upon file upload

_pdbx_database_status.entry_id                    	VP2_PENTAMER_ITIH4_VWFA
_pdbx_database_status.status_code                 	.
_pdbx_database_status.status_code_sf              	?
_pdbx_database_status.status_code_mr              	?
_pdbx_database_status.status_code_cs              	?
_pdbx_database_status.recvd_initial_deposition_date   ?
_pdbx_database_status.status_code_nmr_data        	?
_pdbx_database_status.deposit_site                	?
_pdbx_database_status.process_site                	?
_pdbx_database_status.SG_entry                    	?
_pdbx_database_status.pdb_format_compatible       	Y
_pdbx_database_status.methods_development_category	?

**Comment by hongsudt** [comment]
The table _pdbx_database_status is included in the json schema document from pyrcsb_db. @svoinea to check whether it is also in the schema.json after the manual conversion. If not what happens to this table since it is not an Ermrest table. 

Proposed solution
- In the ingest script, generate a whitelist (i.e. `script_generated_mmcif_tables` ) which is the same list of tables we insert directly into the final mmCIF. 
- Currently, the code will fail if there is no corresponding table in Ermrest. We will extend this validation to ignore the tables in whitelist. 
```
script_generated_mmcif_tables=[pdbx_database_status,...]
fail if not in ermrest or script_generated_mmcif_tables
```

**Comment by hongsudt** [comment]
This fix will go into the next release. In the meantime, we agreed that we would have to tell users to remove this table from the input mmCIF. @monica81567 @brindakv

**Comment by svoinea** [comment]
Tables in `json-full-db-ihm_dev_full-col-ihm_dev_full.json` but not in `ermrest`:
```
[
    "database_2",
    "pdbx_audit_revision_details",
    "pdbx_audit_revision_history",
    "pdbx_database_status"
]
```
Currently, the backend list excludes from the general writing into mmCIF:
```
    if table_name in ['entry', 'chem_comp_atom', 'database_2', 'ihm_entry_collection', 'ihm_entry_collection_mapping', 'pdbx_audit_revision_details',
                      'pdbx_audit_revision_history', 'pdbx_database_status']:
       continue
```
The `ihm_entry_collection` and `ihm_entry_collection_mapping` are written separately due to their particularities.
 
I have excluded from the mmCIF reading the following:
``` 
        excluded_mmCIF_tables = [
            'entry', 'database_2', 'pdbx_audit_revision_details', 'pdbx_audit_revision_history', 'pdbx_database_status'
        ]
```
It is ready for test on catalog `99`.

**Comment by brindakv** [comment]
@svoinea `excluded_mmCIF_tables` at ingest should have all the tables excluded while writing from ermrest. 
```
excluded_mmCIF_tables = [
            'entry', 'chem_comp_atom', 'database_2', 'ihm_entry_collection', 'ihm_entry_collection_mapping', 'pdbx_audit_revision_details', 'pdbx_audit_revision_history', 'pdbx_database_status'
        ]
```

**Comment by brindakv** [comment]
@svoinea Please see Hongsuda's solution above regarding the list tables (I have updated the list of tables with the correct names). 

> script_generated_mmcif_tables=['database_2', 'ihm_entry_collection', 'ihm_entry_collection_mapping', 'pdbx_audit_revision_details', 'pdbx_audit_revision_history', 'pdbx_database_status']

**Comment by brindakv** [comment]
Looks good on `dev`.
