### ISSUE TITLE
Processing Status v.s. Generated mmCIF processing status

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/protein-database#87]
- Add @brindakv to the email notification when the processing steps fail
- Reset both Record_Status_Detail and Generated mmCIF Processing Status to sync together.
   - @svoinea fixed the syncing of `Generated mmCIF Processing Status` and `Record Status Detail` on dev. @brindakv to review. 
- @svoinea checks when `Generated mmCIF Processing Status` is updated and why do we need this status.
- Consider adding "Generating mmCIF file", to "Processing_Status" vocab table -- @brindakv is this a good status? 
   - Depends on whether `Processing Status` is displayed on Chaise (at present it is not)
- When the mmCIF file is being generated, instead of using `Generated mmCIF Processing Status`, consider using the new status to convey this process. 

@brindakv @svoinea Please add missing items.

**Comment by svoinea** [comment]
The values of the `Vocab.Process_Status` table are:
```
 New
 Renew
 in progress
 success
 ERROR
```
The tables `entry` and `Entry_Related_File` have the following columns:
```
Process_Status
Workflow_Status
Record_Status_Detail
```
In addition, the `entry` table has the `Generated_mmCIF_Processing_Status` column (`NOT` a FK to a vocabulary table) with the following values:
```
 in progress
 success
 ERROR
```
Once the user changes the `Workflow_Status` to the `SUBMIT` value, the trigger changes the `Generated_mmCIF_Processing_Status` to the `in progress` value.
After the backend process finishes, the `Generated_mmCIF_Processing_Status` becomes `success` or `ERROR`.

The `Process_Status` is used for starting the backend processes:
```
process_mmCIF when Process_Status in (New, Renew) and Workflow_Status=DEPO
export_mmCIF when Process_Status in (New, Renew) and Workflow_Status=SUBMIT
set_accession_code when Process_Status=success and Workflow_Status=SUBMISSION COMPLETE
addReleaseRecords when Process_Status=success and Workflow_Status=RELEASE READY
```
The trigger sets the value for the `Process_Status` to `Renew` when the `Workflow_Status` is in (DEPO, SUBMIT), starting thus the `process_mmCIF` and `export_mmCIF` backend processes.

The `process_Entry_Related_File` is triggered when `Process_Status` is in (New, Renew) and `Workflow_Status`= DEPO and the `Process_Status` of the `entry` table is `success`.
The trigger sets the value for the `Process_Status` to `Renew` when the `Workflow_Status` = DEPO, starting thus the `process_Entry_Related_File` backend process.

**Comment by svoinea** [comment]
`Process_Status` is now visible on catalog `99` next to the `Workflow_Status` in the `compact` and `details` views.

Current values:
```
 New
 Renew
 in progress
 success
 ERROR
```

Suggested new values:
```
 New
 Reprocess
 Depositing mmCIF in progress
 Generating mmCIF in progress
 Generating the accession code in progress
 Generating the released mmCIF in progress
 Success
 Error
```

**Comment by brindakv** [comment]
Questions: 
1. What is `entry.Process_Status` when `entry.Workflow_Status` is `DRAFT --> DEPO`? 
2. What is `entry.Process_Status` when `entry.Workflow_Status` is `SUBMIT`, `SUBMISSION COMPLETE` and `RELEASE READY`?
3. What is `entry.Process_Status` and `entry.Workflow_Status` when `Uploaded_Restraint_Files.Workflow_Status` is `DRAFT --> DEPO` and `DEPO --> ERROR / RECORD READY`? 
4. Does `Uploaded_Restraint_Files.Process_Status` exist? If yes, what is it set to when `Uploaded_Restraint_Files.Workflow_Status` is `DRAFT --> DEPO` and `DEPO --> ERROR / RECORD READY` as well as for the rest of workflow handled by the `entry` table? 
5. In general, at what workflow steps is `entry.Process_Status` (and `Uploaded_Restraint_Files.Process_Status`) reset?

**Comment by svoinea** [comment]
1. To trigger the processing `DRAFT --> DEPO`, the `Process_Status` needs to be `New` or `Renew` (should be renamed to `Reprocess`).
2. For `SUBMIT` it needs to be `New` or `Renew`. For `SUBMISSION COMPLETE` and `RELEASE READY` it needs to be `success`.
3. `entry.Process_Status` needs to be `success`, `Entry_Related_File.Workflow_Status` needs to be `DEPO` and `Entry_Related_File.Process_Status` needs to be `New` or `Renew`.
4. Yes. Initially it is `New`. A trigger defined while updating its `Workflow_Status` can change it to `Renew`.
5. The reset occurs through a trigger each time the `Workflow_Status` is changed.

**Comment by brindakv** [comment]
Follow up after discussion on June 8th, 2022: 

1. Make `Workflow_Status` and `Process_Status` descriptions better for users to understand the preceding and following steps in the workflow.
2. Make `Entry_Related_File.Process_Status` visible on chaise. 
3. Vocab terms for `Process_Status`: 
```
 New (trigger backend process)
 Reprocess (trigger backend process after Error)
 In progress: processing uploaded mmCIF file
 In progress: generating mmCIF file
 In progress: generating accession code
 In progress: releasing entry
 Success
 Resume (trigger backend process)
 Error: processing uploaded mmCIF file
 Error: generating mmCIF file
 Error: generating accession code
 Error: releasing entry
 In progress: processing uploaded restraint files
 Error: processing uploaded restraint files
```
4. Update chaise annotation: In `Entry_Related_File`, change `Workflow Status` to `Uploaded Restraints Workflow Status` and `Process Status` to `Uploaded Restraints Process Status`
5. Mask the controlled vocabulary terms of `Entry_Related_File.Workflow_Status` to show only the relevant terms: `DRAFT, DEPO, RECORD READY and ERROR`.
6. `Entry_Related_File.Process_Status` values are controlled by the backend (i.e., the values are not editable by user or curator but is visible to user and curator) and the only values it can take are `New, Reprocess, In progress: processing uploaded restraint files, Error: processing uploaded restraint files, Success`.

**Comment by hongsudt** [comment]
@svoinea in the annotation, you apply the filter so that `Restraint_Status` is true, correct?

**Comment by svoinea** [comment]
Correct.

**Comment by brindakv** [comment]
In catalog `99`, when `Workflow_Status` is set to `DEPO` for a new entry, `Process_Status` shows `New (trigger backend process)`. I don't see this vocabulary term with the parentheses [here](https://data.pdb-dev.org/chaise/recordset/#1/Vocab:Process_Status@sort(RID)).

**Comment by svoinea** [comment]
`Record_Status_Detail` should be now visible on all catalogs, inclusive for `submitter`.

**Comment by brindakv** [comment]
These are the issues observed while testing on catalog 99: 
 - After `Error: processing uploaded mmCIF file`, `Resume (trigger backend process)` is shown instead of `Reprocess (trigger backend process after Error)`. Note: After `Error: generating mmCIF file`, `Reprocess (trigger backend process after Error)` is shown correctly. 
 - `In progress: processing uploaded mmCIF file`, `In progress: generating mmCIF file` `In progress: generating accession code`,  and `In progress: releasing entry` are not seen. 
 - `Process Status` does not change to `Resume (trigger backend process)` or `In progress: generating accession code` when the `Workflow Status` is changed to `SUBMISSION COMPLETE` by the curator. It still shows `Success` from the previous step.
 -  Note that mmCIF file is not regenerated or validated during `SUBMISSION COMPLETE --> HOLD`
 - `Process Status` does not change to `Resume (trigger backend process)` or `In progress: releasing entry` when the `Workflow Status` is changed to `RELEASE READY` by the curator. It still shows `Success` from the previous step. 
 - When there is an error after `Workflow Status` is set to `RELEASE READY`, the `Process Status` shows `Error: generating mmCIF file` instead of `Error: releasing entry`. But the `Record Status Detail` correctly shows a message regarding mmCIF validation failure. After fixing the error and resetting the `Workflow Status` to `RELEASE READY`, `Process Status` is not updated to `Resume (trigger backend process)` or `In progress: releasing entry` and it still shows `Error: generating mmCIF file` from the previous step. The workflow does not proceed to `REL` at this stage. 
 - Unable to test `Process Status` = `Error: generating accession code` 
 -  `Submit` controlled vocabulary term of `Entry_Related_File.Workflow_Status` is not seen
 -  Review the order and description: https://dev.pdb-dev.org/chaise/recordset/#99/Vocab:Process_Status@sort(RID)
 -  `Restraint Workflow Status` and `Restraint Process Status` in `Entry_Related_File` needs to be tested.

**Comment by svoinea** [comment]
@brindakv I have updated the triggers as well as the backend code.
I think most of the status values are fixed now.
If possible, please retest them.

**Comment by brindakv** [comment]
Testing `Entry_Related_File.Process_Status` and `Entry_Related_File.Workflow_Status` on catalog `99`: 

 - When `DEPO` is re-triggered (after `New` or `Error`), `Resume (trigger backend process)` is shown instead of `Reprocess (trigger backend process after Error)`.
 
 - When `DEPO` is re-triggered (after `New`), the rows populated in the corresponding table referenced by `Entry_Related_File.File_Type` in the previous load are not deleted.
 
 - `Record_Status_Detail` column is not shown in detailed view.
 
 - `Record_Status_Detail` is not populated when there is an error (both curator and user cannot see the error message). Not sure if the error is because of not deleting previously loaded information or because of the error that was created for testing purposes. 
 
 - `Entry_Related_File.Workflow_Status` defaults to `DRAFT` when changed from any other state (e.g., `ERROR` or `RECORD READY`). It can only change to `DEPO` when triggered after `DRAFT`.

**Comment by brindakv** [comment]
@svoinea I will retest `entry.Process_Status` and `entry.Workflow_Status` on catalog `99`.

**Comment by brindakv** [comment]
@svoinea all tasks above have been addressed on `Dev` and can be deployed on `Production`. Please make sure that the automated workflow emails are sent only on `Dev` and not on `Production`.

**Comment by brindakv** [comment]
@svoinea New issue: 
`Entry_Related_File.Process_Status` shows `Resume (trigger backend process)` when new file is uploaded after `Entry_Related_File.Workflow_Status = ERROR`. This should be `Reprocess (trigger backend process after Error)`.

**Comment by brindakv** [comment]
@svoinea all issues have been addressed. Can be deployed on production.
