### ISSUE TITLE
Adding rows to be tables that are already full

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/protein-database#9]
The unique keys for some tables are foreign keys pointing to a parent. In such cases, adding rows to an already full table (based on the rows in the parent tables) should be disallowed. 

For instance, the key for entity_poly table is _entity_poly.entity_id that points to _entity.id in the entity table. Adding more rows this table should be disallowed unless an existing row is deleted or the parent table is updated. 

At present, an error is shown when submitting a new row to this table (see screen shot below), but it is not clear why a different combination of entity_id, structure_id should be used because any combination will give the same error. It would be better if adding rows to full tables are disallowed. 

![Screen Shot 2019-05-17 at 10 57 02 AM](https://user-images.githubusercontent.com/15000874/57936803-9ca30b00-7892-11e9-99e2-1b8a8f801bfb.png)

**Comment by carlkesselman** [comment]
Ok, so I think the issue here is that we are using a composite key to connect these records and if you don’t know how to create the unique combination you will get an error.  Perhaps a better approach here is to use the RID to link these records, and then the picker will give you the actual entity you want.  This is an instance where the model that you gave us is actually correct, but in practice we need to refactor a bit to make it easier to navigate.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On May 17, 2019, at 8:15 AM, Brinda Vallat <notifications@github.com<mailto:notifications@github.com>> wrote:


The unique keys for some tables are foreign keys pointing to a parent. In such cases, adding rows to an already full table (based on the rows in the parent tables) should be disallowed.

For instance, the key for entity_poly table is _entity_poly.entity_id that points to _entity.id<http://entity.id> in the entity table. Adding more rows this table should be disallowed unless an existing row is deleted or the parent table is updated.

At present, an error is shown when submitting a new row to this table (see screen shot below), but it is not clear why a different combination of entity_id, structure_id should be used because any combination will give the same error. It would be better if adding rows to full tables are disallowed.

[Screen Shot 2019-05-17 at 10 57 02 AM]<https://user-images.githubusercontent.com/15000874/57936803-9ca30b00-7892-11e9-99e2-1b8a8f801bfb.png>

**Comment by carlkesselman** [comment]
Another approach might be to put a filter in the dropdown so you are only given the correct options…..

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On May 17, 2019, at 8:23 AM, Carl Kesselman <carl@isi.edu<mailto:carl@isi.edu>> wrote:

Ok, so I think the issue here is that we are using a composite key to connect these records and if you don’t know how to create the unique combination you will get an error.  Perhaps a better approach here is to use the RID to link these records, and then the picker will give you the actual entity you want.  This is an instance where the model that you gave us is actually correct, but in practice we need to refactor a bit to make it easier to navigate.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On May 17, 2019, at 8:15 AM, Brinda Vallat <notifications@github.com<mailto:notifications@github.com>> wrote:


The unique keys for some tables are foreign keys pointing to a parent. In such cases, adding rows to an already full table (based on the rows in the parent tables) should be disallowed.

For instance, the key for entity_poly table is _entity_poly.entity_id that points to _entity.id<http://entity.id/> in the entity table. Adding more rows this table should be disallowed unless an existing row is deleted or the parent table is updated.

At present, an error is shown when submitting a new row to this table (see screen shot below), but it is not clear why a different combination of entity_id, structure_id should be used because any combination will give the same error. It would be better if adding rows to full tables are disallowed.

[Screen Shot 2019-05-17 at 10 57 02 AM]<https://user-images.githubusercontent.com/15000874/57936803-9ca30b00-7892-11e9-99e2-1b8a8f801bfb.png>

**Comment by ytfqj** [comment]
Currently, when structure_id is selected,  there is a filter applied then a user could only see the options related to that structure_id.
the error "The entry cannot be created/updated. Please use a different combination of entity_id, structure_id for this record." is caused by primary_key constraint (structure_id,entity_id).
Even the table is not full if user select existing (structure_id,entity_id), this error will show too.

**Comment by brindakv** [comment]
That is right. Even if the table is not full, if an existing structure_id, entity_id combination is chosen, the same error will pop up. But in that case, the error clearly indicates that the user should choose a different combination. When the table if full, adding more rows should be disallowed because of the primary_key constraint and a different error message can be shown.

**Comment by hongsudt** [comment]
Address by TOC arrangement and training material. 
We should improve the error message.
